-- MySQL Script generated by MySQL Workbench
-- Fri Sep 30 13:17:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8 ;
USE `escola` ;

-- -----------------------------------------------------
-- Table `escola`.`apostila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escola`.`apostila` (
  `idapostila` INT NOT NULL AUTO_INCREMENT,
  `NomeAp` VARCHAR(255) NOT NULL,
  `dataPubliAP` DATE NOT NULL,
  `DescAp` TEXT NOT NULL,
  `nomeArqAp` VARCHAR(100) NOT NULL,
  `dataCadAp` DATE NOT NULL,
  `capaAp` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idapostila`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
