SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `artigos` DEFAULT CHARACTER SET utf8 ;
USE `artigos` ;

-- -----------------------------------------------------
-- Table `artigos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artigos`.`usuarios` (
  `idproduto` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `marca` VARCHAR(100) NOT NULL,
  `quantidade` VARCHAR(40) NOT NULL,
  `dataVencimento` DATE NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
