-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 11:05:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema artigos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artigos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artigos` DEFAULT CHARACTER SET utf8 ;
USE `artigos` ;

-- -----------------------------------------------------
-- Table `artigos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artigos`.`usuarios` (
  `idusuario` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(40) NOT NULL,
  `dataCad` DATE NOT NULL,
  `tipoUser` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artigos`.`artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artigos`.`artigos` (
  `idartigos` INT NOT NULL AUTO_INCREMENT,
  `tituloArt` VARCHAR(250) NOT NULL,
  `txtArt` TEXT NOT NULL,
  `dataCadArt` DATE NOT NULL,
  `usuarios_fk` INT NOT NULL,
  PRIMARY KEY (`idartigos`),
  INDEX `fk_artigos_usuarios1_idx` (`usuarios_fk` ASC) ,
  CONSTRAINT `fk_artigos_usuarios1`
    FOREIGN KEY (`usuarios_fk`)
    REFERENCES `artigos`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artigos`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artigos`.`comentarios` (
  `idcom` INT NOT NULL,
  `txtcom` TEXT NOT NULL,
  `dataCom` DATE NOT NULL,
  `usuarios_fk` INT NOT NULL,
  `artigos_fk` INT NOT NULL,
  PRIMARY KEY (`idcom`),
  INDEX `fk_comentarios_usuarios1_idx` (`usuarios_fk` ASC) ,
  INDEX `fk_comentarios_artigos1_idx` (`artigos_fk` ASC) ,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`usuarios_fk`)
    REFERENCES `artigos`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_artigos1`
    FOREIGN KEY (`artigos_fk`)
    REFERENCES `artigos`.`artigos` (`idartigos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
